plugins {
    id "com.android.application"
}

android {
    namespace "com.vision.app"
    compileSdk 34

    defaultConfig {
        applicationId "com.vision.app"
        minSdk 26
        targetSdk 34
        versionCode 19
        versionName "0.10.0"
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
