plugins {
    id "com.android.application"
}

android {
    namespace "com.vision.app"
    compileSdk 34

    defaultConfig {
        applicationId "com.vision.app"
        minSdk 26
        targetSdk 34
        versionCode 22
        versionName "0.12.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
    androidTestImplementation "androidx.test:core:1.5.0"
    androidTestImplementation "androidx.test.ext:junit:1.1.5"
    androidTestImplementation "androidx.test:runner:1.5.2"
}
